export const SCREEN_NAAMES = {
HOME:"HOME",
CATEGORY_PAGE:"CATEGORY_PAGE",
PRODUCT_PAGE:"PRODUCT_PAGE",
LOGIN_PAGE:"LOGIN_PAGE",
SIGN_UP:"SIGN_UP",
AI_PAGE:"AI ",
ORDER_PAGE:"ORDERS",
PROFILE_PAGE:"PROFILE",

}