export const SCREEN_NAAMES = {
HOME:"HOME",
CATEGORY_PAGE:"CATEGORY_PAGE",
PRODUCT_PAGE:"PRODUCT_PAGE",
CART_PAGE:"CART_PAGE",
LOGIN_PAGE:"LOGIN_PAGE",
SIGN_UP:"SIGN_UP",
ORDER_PAGE:"ORDER_PAGE",
ORDER_SUCCESS_PAGE:"ORDER_SUCCESS_PAGE",
ORDER_FAIL_PAGE:"ORDER_FAIL_PAGE",
PROFILE_PAGE:"PROFILE_PAGE",
}